spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Solo exponer health en producción
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Logs mínimos en producción
logging.level.com.expressvraem=WARN
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
